const dayjs = require('dayjs')
const date1 = dayjs().format('YYYY-MM-DD')
const date2 = dayjs().subtract(1, 'months').format('YYYY-MM-DD')
const date3 = dayjs().subtract(2, 'months').format('YYYY-MM-DD')

module.exports = [
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1111,
    Current: 1112,
    Limit: 1113,
    Type: 'depository',
    Subtype: 'checking',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 4500,
    Current: 500,
    Limit: 5000,
    Type: 'credit',
    Subtype: 'credit card',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 555,
    Current: 556,
    Limit: 557,
    Type: 'asset',
    Subtype: 'asset',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2000,
    Current: 2000,
    Limit: 2000,
    Type: 'asset',
    Subtype: 'vehicle',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID5',
    Name: 'Name5',
    OfficialName: 'OfficialName5',
    Available: 1999,
    Current: 1999,
    Limit: 1999,
    Type: 'loan',
    Subtype: 'vehicle loan',
    RetrievalDate: date1,
  },
  /////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1311,
    Current: 1312,
    Limit: 1313,
    Type: 'depository',
    Subtype: 'checking',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 4450,
    Current: 550,
    Limit: 5000,
    Type: 'credit',
    Subtype: 'credit card',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 455,
    Current: 456,
    Limit: 457,
    Type: 'asset',
    Subtype: 'asset',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2100,
    Current: 2100,
    Limit: 2100,
    Type: 'asset',
    Subtype: 'vehicle',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID5',
    Name: 'Name5',
    OfficialName: 'OfficialName5',
    Available: 2200,
    Current: 2200,
    Limit: 2200,
    Type: 'loan',
    Subtype: 'vehicle loan',
    RetrievalDate: date2,
  },
  /////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1211,
    Current: 1212,
    Limit: 1213,
    Type: 'depository',
    Subtype: 'checking',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 4600,
    Current: 400,
    Limit: 5000,
    Type: 'credit',
    Subtype: 'credit card',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 155,
    Current: 156,
    Limit: 157,
    Type: 'asset',
    Subtype: 'asset',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2200,
    Current: 2200,
    Limit: 2200,
    Type: 'asset',
    Subtype: 'vehicle',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID5',
    Name: 'Name5',
    OfficialName: 'OfficialName5',
    Available: 2400,
    Current: 2400,
    Limit: 2400,
    Type: 'loan',
    Subtype: 'vehicle loan',
    RetrievalDate: date3,
  },
]
