const dayjs = require('dayjs')
const date1 = dayjs().format('YYYY-MM-DD')
const date2 = dayjs().subtract(1, 'months').format('YYYY-MM-DD')
const date3 = dayjs().subtract(2, 'months').format('YYYY-MM-DD')

module.exports = [
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1111,
    Current: 1112,
    Limit: 1113,
    Type: 'depository',
    Subtype: 'checking',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 2221,
    Current: 2222,
    Limit: 2223,
    Type: 'depository',
    Subtype: 'asset',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 3000,
    Current: 3000,
    Limit: 3000,
    Type: 'loan',
    Subtype: 'vehicle loan',
    RetrievalDate: date1,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2000,
    Current: 2000,
    Limit: 2000,
    Type: 'Asset',
    Subtype: 'HSA',
    RetrievalDate: date1,
  },
  /////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1221,
    Current: 1222,
    Limit: 1223,
    Type: 'depository',
    Subtype: 'Subtype',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 2331,
    Current: 2332,
    Limit: 2333,
    Type: 'depository',
    Subtype: 'Subtype',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 3441,
    Current: 3442,
    Limit: 3443,
    Type: 'loan',
    Subtype: 'Subtype',
    RetrievalDate: date2,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2220,
    Current: 2220,
    Limit: 2220,
    Type: 'Asset',
    Subtype: 'Subtype',
    RetrievalDate: date2,
  },
  /////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////
  {
    UserID: 1,
    AccountID: 'AccountID1',
    Name: 'Name1',
    OfficialName: 'OfficialName1',
    Available: 1001,
    Current: 1002,
    Limit: 1003,
    Type: 'depository',
    Subtype: 'Subtype',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID2',
    Name: 'Name2',
    OfficialName: 'OfficialName2',
    Available: 2111,
    Current: 2112,
    Limit: 2113,
    Type: 'depository',
    Subtype: 'Subtype',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID3',
    Name: 'Name3',
    OfficialName: 'OfficialName3',
    Available: 3551,
    Current: 3552,
    Limit: 3553,
    Type: 'loan',
    Subtype: 'Subtype',
    RetrievalDate: date3,
  },
  {
    UserID: 1,
    AccountID: 'AccountID4',
    Name: 'Name4',
    OfficialName: 'OfficialName4',
    Available: 2330,
    Current: 2330,
    Limit: 2330,
    Type: 'Asset',
    Subtype: 'Subtype',
    RetrievalDate: date3,
  },
]
